### ISSUE TITLE
multiple `stepRange` lead to wrong decoding time 

### ISSUE THREAD

**Issue by oloapinivad** [gribscan/gribscan#19]
Hi there, 

analyzing the most recent data from IFS/FESOM we stepped in one variable which is not decoded as expected - or at least as I expect - by gribscan.

We have an experiment with 6-hour output from IFS, currently available on Levante (I can provide the path), for which we found that one variable, namely `litota1` (Averaged total lightning flash density in the last hour) is incorrectly decoded by gribscan and it is stored in the json (but I imagine also in the original index file) as having the time at 5-11-17-23 hour instead of 6-12-18-24 as all the other variables. 

This does NOT happen if we open the GRIB file directly using `cfgrib`. Further digging into the file show that this inconsistency is due by the fact that the original grib code has a `stepRange`which is "multiple", i.e. it covers two time steps (no clue why this is happening for this specific variabile) instead of one. For some reason, gribscan took the first one, while the real time is of course the second). See the attached screenshot, `litota1` is the last one. 

![Schermata 2023-04-03 alle 14 55 17](https://user-images.githubusercontent.com/28352235/229705195-a9db5583-5e2e-4432-ba8e-d328844c3eff.png)

Do you think this is an expected behaviour of gribscan or something that should be fixed? This leads to the issue of having an irregular time axis in the final xarray, having time 0-5-6-11-12-17-18-23 etc which are NaN every other time. We can certainly filter this a posteriori, but perhaps it can be tackled at the source.  

Many thanks, please let me know if you need further details

**Comment by oloapinivad** [comment]
Actually `stepRange` is produced as the result of `startStep` and `endStep`. The former is set to 5, thus I imagine that the issue starts from here...

**Comment by d70-t** [comment]
Time in GRIB is quite different as compared to the dataset approach, i.e. depending on the message type, GRIB defines quite a bunch of time information. For gribscan, there has to be a bit of guesswork, which transforms all the available pieces of time information into a single point in time to sort the messages into the grid of messages forming the dataset. Most of the guesswork / computation is done [here](https://github.com/gribscan/gribscan/blob/7c60467db493f533f430416ebd0942e2f2d9e06f/gribscan/gribscan.py#L217), however it would be possible to override this in a gribscan Magician for specific datasets.

However, my first guess would be, that this should be handled generically (i.e. not in the Magician) and we just didn't come across the way time is defined in your case so far. Probably the data is encoded somehow as 5h + 1h step? Which then probably should be interpreted as 6h?

**Comment by trackow** [comment]
@oloapinivad , could you maybe link the Levante example file you mentioned on Mattermost here?

**Comment by oloapinivad** [comment]
Yes, here it is an example file

`/work/bb1153/b382173/tco79-0rca1/ICMGGhvi1+000006`

**Comment by d70-t** [comment]
The messages in question seem to specify time as a time range, which raises the question which time point we'd like to have within that time range. Currently the default behavior seems to be the start time point, but likely we'd rather have the end time point as a default.

**Comment by d70-t** [comment]
Can you try the [`lean_towards_end`](https://github.com/gribscan/gribscan/tree/lean_towards_end) branch?

**Comment by trackow** [comment]
Also, @oloapinivad you would need to install gribscan as developer version (clone the repo, change branch to Tobi's version) and then python -m pip install -e <path to your clone>

**Comment by oloapinivad** [comment]
Yep, sorry it took me a sec to create a fresh environment (with eccodes, scipy, etc) and try the branch. 

So there are many operations that can go wrong (env, gribscan calls, etc), but unfortunately I still get the time at 5h. I created a specific mamba env where I installed in dev mode the gribscan `lean_towards_end` branch

Then I run this simple bash script:

```
#!/bin/bash
set -e

# find mamba/conda (to be refined)
whereconda=$(which mamba | rev | cut -f 3-10 -d"/" | rev)
source $whereconda/etc/profile.d/conda.sh

# activate AQUA environment
conda activate gribber

# expid
expid=pippo

# define folder and grib files
tmpdir=/home/b/b382076/scratch/gribscan/$expid
jsondir=/home/b/b382076/work/gribscan-json/$expid
datadir=/work/bb1153/b382173/tco79-0rca1/
gribfiles='ICMGGhvi1+0000*'

# number of parallel procs
nprocs=1

# create folders
mkdir -p $jsondir $tmpdir

# create file links to avoid messing with original data
echo "Linking files..."
for file in $(ls $datadir/$gribfiles) ; do
    ln -sf $file $tmpdir/
done

# creating the indices
echo "Creating GRIB indices..."
cd $tmpdir
gribscan-index $tmpdir/$gribfiles -n $nprocs

# running the json creation
echo "Building JSON file..."
gribscan-build -o $jsondir --magician ifs --prefix $datadir *.index
```

And then I try to open the resulting json

```
import xarray as xr
test = xr.open_zarr('reference::/home/b/b382076/work/gribscan-json/pippo/atm2d.json', consolidated=False)
test.time
```
<img width="932" alt="Schermata 2023-04-04 alle 13 27 05" src="https://user-images.githubusercontent.com/28352235/229777672-0346d134-25ff-4f33-84e0-53616c4ed89c.png">

**Comment by oloapinivad** [comment]
Hi @d70-t, of course there was an error on my side in my script creating the json.
Indeed the index are correct, and now the time axis is aligned. I will check this further to be sure everything is correct, many thanks for the fast fix!

<img width="878" alt="Schermata 2023-04-04 alle 14 41 17" src="https://user-images.githubusercontent.com/28352235/229794721-9cf3854d-23d9-47e7-a830-c773c5cde7a1.png">

**Comment by oloapinivad** [comment]
Hi @d70-t, do you plan to include this fix in the main?
And what is the timeline for having a release for pypi/conda with such fix? Just to decide how to adapt our worflow. 
Many thanks

**Comment by d70-t** [comment]
If you're happy with it, I guess we can do that next week (it holiday here and I guess it would be up to @lkluft).

**Comment by oloapinivad** [comment]
I have just tested it again from scratch, and everything works as it should, so for me it is fine. Next week - but also later this month is perfect for me! Thanks again!

**Comment by lkluft** [comment]
I merged Tobi's fix and created a [new release](https://github.com/gribscan/gribscan/releases/tag/v0.0.6) which is also available on [PyPI](https://pypi.org/project/gribscan/0.0.6/)

**Comment by oloapinivad** [comment]
Thanks @lkluft I will test as soon as I can
