### ISSUE TITLE
Merge fixes for IFS output

### ISSUE THREAD

**Issue by lkluft** [gribscan/gribscan#26]
During the preparation of the NextGEMS hackathon several fixes for IFS output have been tested that didn't find there way back to gribscan, yet. Some of these fixes seem to be useful for other use cases as well. 

* Support for `regular_ll` (implement in a consistent way as #22)
* Do not fail for unknown GRIB definitions

**Comment by trackow** [comment]
Yes, our FDB for Cycle 3 is here: /work/bm1235/a270046/cycle3/multio_cycle3/fdb.dir.multio/

In there you find different streams. Would be good to test it for an example file from all of those streams, at least for the bold ones to test across different grids and frequencies:

**rd:hzfy:lwda:20200120:0000:g (hourly, native high res grid)**
rd:hzfy:monr:20200115:0000:g (monthly means, native high res grid)

**rd:hzfy:msda:g (monthly, regular grid)
rd:hzfy:mdfa:g (monthly, regular grid)**

rd:hzfy:scda:20200120:0000:g (hourly, regular grid)
rd:hzfy:dcda:20200120:0000:g (hourly, regular grid)

**rd:hzfy:lwwv:20200120:0000:g (wave model output)**

**Comment by lkluft** [comment]
I tested `gribscan-index` on random files from each of the highlighted directories. I was able to always create indices without crashes and also create datasets using `gribscan-build -m ifs`. In my opinion, we can close this issue and see how far we come during the preparation of the next hackathon
