### ISSUE TITLE
gribscan with spherical harmonics data

### ISSUE THREAD

**Issue by SF-N** [gribscan/gribscan#55]
Hi, 
I am trying to read large remote GRIB file containing spherical harmonics data using gribscan:

```python
import argparse

import gribscan
import uuid
from pathlib import Path


upload_path = Path("hplp/test_hplp_ml_sh.grib")
	
index_path = Path(".") / f"{upload_path.stem}.{uuid.uuid4()}.index"
gribscan.write_index(str(upload_path), index_path)
class MyIFSMagician(gribscan.magician.IFSMagician):
    def variable_hook(self, key, info):
        var = super().variable_hook(key, info)
        var["attrs"] = dict(**var["attrs"], **info.get("extra", dict()))
        
        return var
        
magician = MyIFSMagician()
ref = gribscan.grib_magic([index_path], magician)

import json

ref = json.loads(json.dumps(ref).replace(
    json.dumps(str(upload_path)),
    json.dumps("https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/hplp/test_hplp_ml_sh.grib"),
))

ref = next(iter(ref.values()))
json_object = json.dumps(ref, indent=4)

with open(f"{upload_path}.ref", "w") as outfile:
    outfile.write(json_object)
```
This results in the following error, as gribscan appears to have no support for "sh" grids:
```
Traceback (most recent call last):
  File "/Users/ecm5945/Documents/ECMWF/Code/data_compression/compression-lab-notebooks/tmp.py", line 22, in <module>
    ref = gribscan.grib_magic([index_path], magician)
  File "/Users/ecm5945/Documents/ECMWF/Code/data_compression/venv/lib/python3.10/site-packages/gribscan/gribscan.py", line 630, in grib_magic
    global_attrs, coords, varinfo = inspect_grib_indices(messages, magician)
  File "/Users/ecm5945/Documents/ECMWF/Code/data_compression/venv/lib/python3.10/site-packages/gribscan/gribscan.py", line 464, in inspect_grib_indices
    **magician.extra_coords(varinfo),
  File "/Users/ecm5945/Documents/ECMWF/Code/data_compression/venv/lib/python3.10/site-packages/gribscan/magician.py", line 133, in extra_coords
    return varinfo2coords(v0)
  File "/Users/ecm5945/Documents/ECMWF/Code/data_compression/venv/lib/python3.10/site-packages/gribscan/gridutils.py", line 102, in varinfo2coords
    grid = grids[varinfo["attrs"]["gridType"]]
KeyError: 'sh'
```
With reduced_gg data, the above code works perfectly fine.

The sh data is available at: https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/hplp/test_hplp_ml_sh.grib.
Do you have any suggestions on how to create a JSON file for this dataset in order to read it remotely?

**Comment by d70-t** [comment]
In order for gribscan to be able to build datasets with a grid, gribscan needs to know which grid-defining parameters must be kept in the index. As we didn't yet have sh grids, no one looked that up so far. To add data on sh grid, you'd have to add an appropriate class to [the gridutils file](https://github.com/gribscan/gribscan/blob/main/gribscan/gridutils.py#L13). Basically you need to list all eccodes keys which you plan to use for computing the grid coordinates (this could also be empty, if you don't want to add coordinates).

**Comment by SF-N** [comment]
Great, thanks a lot for the quick replies! I tried the same, but with `params = []` and `def compute_coords(cls)`.
Both options seem to work fine. What is the benefit of having the params?

**Comment by lkluft** [comment]
I'm absolutely no expert on spherical harmonics and just wanted to show how you can use them in theory 😉 If you're not going to do anything with them, you can leave them out.

**Comment by SF-N** [comment]
Thanks! Would you like me to open a PR with the new subclass?

**Comment by lkluft** [comment]
Yes, we'd really appreciate it :)

**Comment by SF-N** [comment]
Please see PR #56
